### ISSUE TITLE
Je moet de back-ends apart op starten

### ISSUE THREAD

**Issue by Dennis-APPELS** [TaxModel-coding-team/Onboardify-Tjiftjaf#17]
Zoals het project huidig in elkaar zit moeten we alle back-end services één voor één opstarten. We moeten kijken of we ze allemaal met elkaar kunnen opstarten zodat we de applicatie in zijn geheel kunnen testen.

**Comment by SjoerdJoosen** [comment]
![image](https://user-images.githubusercontent.com/74779345/171633200-49fab4ba-ac5d-4f12-9981-276d49dda664.png)

Je kunt meerdere start-up projects selecteren om zo tegelijk meerdere backends te runnen.
