### ISSUE TITLE
Download QR Code - 2pts

### ISSUE THREAD

**Issue by SjoerdJoosen** [TaxModel-coding-team/Onboardify-Tjiftjaf#38]
Zorg ervoor dat de gebruiker de QR Code kan downloaden als een PNG met behulp van een download button. #30

**Comment by Lucasje2** [comment]
QR code downloaden is niet mogelijk met de huidige QR-code generatie in de front-end doormiddel van een knop. 

De beste manier om de QR-code nu te downloaden is right-klikken op de qr-code en deze opslaan als.
